name       : haskell-annotated-wl-pprint
version    : 0.7.0
release    : 2
source     :
    - https://hackage.haskell.org/package/annotated-wl-pprint-0.7.0/annotated-wl-pprint-0.7.0.tar.gz : 0c262d7fe13a9a50216438ec882c13e25f31236b886a5692e3c35b85cd773d18
license    : BSD-3-Clause
component  : programming.haskell
summary    : This is a modified version of wl-pprint, which was based on Wadler's
    paper A Prettier Printer
description: |
    This is a modified version of wl-pprint, which was based on Wadler's paper A Prettier Printer
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
