name       : haskell-annotated-wl-pprint
version    : 0.7.0
release    : 1
source     :
    - https://hackage.haskell.org/package/annotated-wl-pprint-0.7.0/annotated-wl-pprint-0.7.0.tar.gz : 0c262d7fe13a9a50216438ec882c13e25f31236b886a5692e3c35b85cd773d18
license    : BSD-3-Clause
component  : programming
summary    : This is a modified version of wl-pprint, which was based on Wadler's paper A Prettier Printer
description: |
    This is a modified version of wl-pprint, which was based on Wadler's paper A Prettier Printer
builddeps  :
    - ghc
setup      : |
    sudo ghc-pkg recache
    ghc -threaded Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --datadir=/usr/share \
                      --sysconfdir=/etc \
                      --libexecdir=/usr/lib64/cabal \
                      --libsubdir="\$compiler/\$pkgid"
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 annotated-wl-pprint-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/annotated-wl-pprint-$version.conf
